import React, { useEffect, useState } from 'react';
import { ArrowRight, Check, Clock3, Coins, FileText, Search, ShieldCheck, Zap } from 'lucide-react';
import './agentStatus.css';

const money = (value) => `₹${Math.round(value || 0).toLocaleString('en-IN')}`;
const Button = ({ children, onClick, disabled, secondary }) => <button className={secondary ? 'button button-secondary' : 'button'} onClick={onClick} disabled={disabled}>{children}</button>;
const Info = ({ label, value }) => <div className="info"><small>{label}</small><b>{value}</b></div>;

export default function BuyerJourneyInteractive({ session, liveEvents = [], buyerDecision, prompt, setPrompt, loading, run, post, request, onUpsellDecision }) {
  const [upsell, setUpsell] = useState(null);
  const state = session?.intent_spec ? (session.current_state || 'INTENT_RECEIVED') : 'READY';
  const intent = session?.intent_spec;
  const selected = session?.selected_offer;
  useEffect(() => { if (!selected?.product_id) { setUpsell(null); return undefined; } let active = true; request('/agent/upsell/quote', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ base_product_id: selected.product_id, session_id: session.session_id }) }).then((result) => { if (active) setUpsell(result); }).catch(() => { if (active) setUpsell(null); }); return () => { active = false; }; }, [selected?.product_id, session?.session_id, request]);
  const liveOffers = liveEvents.filter((event) => event.event_type === 'MERCHANT_OFFER_RECEIVED' && event.payload?.offer).map((event) => event.payload.offer);
  const offers = [...(session?.received_offers || []), ...liveOffers].filter((offer, index, items) => items.findIndex((item) => item.offer_id === offer.offer_id) === index);
  const tokens = (intent?.raw_prompt ? Math.ceil(intent.raw_prompt.length / 4) : 0) + (session?.received_offers?.length || 0) * 46 + (session?.audit_logs?.length || 0) * 18;
  const eventTypes = [...(session?.audit_logs || []), ...liveEvents].map((event) => event.event_type);
  const has = (...types) => types.some((type) => eventTypes.includes(type));
  const addOnDecision = buyerDecision?.decision;
  const steps = [
    { number: '01', label: 'CUSTOMER', title: 'Prompt captured', done: Boolean(intent) || has('INTENT_EXTRACTED'), icon: Zap, content: intent ? <div className="chain-details"><Info label="Category" value={intent.product_category} /><Info label="Budget" value={money(intent.budget.max)} /><Info label="Use case" value={intent.use_case} /><Info label="Confidence" value={`${Math.round(intent.confidence_score * 100)}%`} /></div> : <p>Enter what you want to buy and send the prompt to the merchant side.</p>, action: <><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} /><Button onClick={() => run('Intent extraction', () => post('/commerce/intent/extract', { prompt, session_id: session.session_id }))} disabled={loading || !session}>{loading ? 'Processing...' : <>Send prompt <ArrowRight size={15} /></>}</Button></> },
    { number: '02', label: 'DISCOVERY', title: 'Merchant-side agents responding', done: Boolean(session?.received_offers?.length) || has('OFFERS_RECEIVED'), active: offers.length > 0, icon: Search, content: offers.length ? <div className="chain-offers">{offers.map((item) => <div className="chain-offer" key={item.offer_id}><span><b>{item.merchant_name}</b><small><i className="agent-running-dot" /> RUNNING · {item.merchant_name} Merchant Agent</small><small>{item.product_title}</small></span><strong>{money(item.price)}</strong></div>)}</div> : <p>Merchant-side agents will appear here as they respond.</p>, action: <Button secondary onClick={() => run('Discovery and scoring', () => request(`/commerce/orchestrate/discover-and-score?session_id=${session.session_id}`, { method: 'POST' }))} disabled={loading || !intent}>Broadcast query</Button> },
    { number: '03', label: 'POLICY GATE', title: 'Authorization boundary', done: has('AUTHORIZATION_EVALUATED', 'USER_APPROVAL_GRANTED') || ['AUTHORIZED', 'ORDER_CREATED', 'PAYMENT_INITIATED', 'PAYMENT_VERIFIED', 'PURCHASE_COMPLETED'].includes(state), icon: ShieldCheck, content: selected ? <><div className="selected-product"><small>Selected offer</small><b>{selected.product_title}</b><strong>{money(selected.price)}</strong></div>{upsell && <div className="frequently-bought"><small>FREQUENTLY BOUGHT TOGETHER · {upsell.status === 'PENDING_APPROVAL' ? 'MERCHANT APPROVAL REQUIRED' : addOnDecision ? `CUSTOMER ${addOnDecision}` : 'CUSTOMER DECISION REQUIRED'}</small><div><span>{selected.product_title}<b>{money(selected.price)}</b></span><span>+ {upsell.recommended_product_title}<b>{money(upsell.price)}</b></span><strong>Bundle total {money(addOnDecision === 'ACCEPT' ? selected.price + upsell.price : selected.price)}</strong></div><p>{upsell.status === 'PENDING_APPROVAL' ? upsell.reason : addOnDecision ? `Customer chose to ${addOnDecision === 'ACCEPT' ? 'add this item' : 'keep the main item only'}.` : 'The merchant approved this recommendation. The customer must decide whether to add it.'}</p>{upsell.status === 'AVAILABLE' && !addOnDecision && state === 'AUTHORIZED' && <div className="upsell-actions"><Button onClick={() => onUpsellDecision(true)} disabled={loading}>Add to purchase</Button><Button secondary onClick={() => onUpsellDecision(false)} disabled={loading}>Keep main item</Button></div>}</div>}<p>{session.authorization_result?.reason || 'Evaluating policy...'}</p></> : <p>Complete discovery to evaluate the purchase against policy.</p>, action: <>{state === 'AWAITING_AUTHORIZATION' && <Button onClick={() => run('Policy approval', () => post('/commerce/policy/grant-user-approval', { session_id: session.session_id }))}>Approve purchase</Button>}{state === 'AUTHORIZED' && <Button onClick={() => run('Razorpay order', () => request(`/commerce/transaction/create-razorpay-order?session_id=${session.session_id}`, { method: 'POST' }))}>Create Razorpay order</Button>}</> },
    { number: '04', label: 'VERIFICATION', title: 'Payment and recovery', done: state === 'PURCHASE_COMPLETED' || has('PAYMENT_VERIFIED', 'PURCHASE_COMPLETED'), icon: ShieldCheck, content: session?.recovery_plan ? <><b>Recovery plan ready</b><p>{session.recovery_plan.action_description}</p></> : <p>{session?.is_completed ? 'Order confirmed and merchant notified.' : 'Payment proof and recovery status will appear here.'}</p>, action: <>{state === 'ORDER_CREATED' && <Button onClick={() => run('Payment verification', () => request(`/commerce/transaction/simulate-success?session_id=${session.session_id}`, { method: 'POST' }))}><Check size={15} /> Simulate successful payment</Button>}{session?.recovery_plan && <Button secondary onClick={() => run('Recovery action', () => request(`/commerce/transaction/execute-recovery?session_id=${session.session_id}`, { method: 'POST' }))}>Execute bounded recovery</Button>}</> }
  ].map((step) => ({ ...step, action: step.done ? null : step.action }));
  return <><section className="hero"><div><p className="eyebrow">LIVE TRANSACTION WORKSPACE</p><h2>Make every agent decision<br /><em>visible and accountable.</em></h2><p>Translate customer intent into a verified purchase with explicit policy gates, merchant reasoning, and bounded recovery.</p></div><div className="hero-state"><span>Current state</span><b>{state}</b><small><i /> Session active</small></div></section><div className="stats"><div className="stat"><small><Clock3 size={14} /> Workflow state</small><b>{state.replaceAll('_', ' ')}</b><em>Deterministic FSM</em></div><div className="stat"><small><FileText size={14} /> Audit events</small><b>{session?.audit_logs?.length || 0}</b><em>Recorded this session</em></div><div className="stat"><small><Coins size={14} /> Token estimate</small><b>{tokens}</b><em>Client-side estimate</em></div><div className="stat"><small><ShieldCheck size={14} /> Recovery budget</small><b>{session?.recovery_attempts || 0} / {session?.max_recovery_attempts || 1}</b><em>Attempts consumed</em></div></div><div className="workflow-chain">{steps.map(({ number, label, title, done, active, icon: Icon, content, action }, index) => <section className={done ? 'workflow-step done' : active ? 'workflow-step active' : 'workflow-step'} key={number}><div className="workflow-rail"><span className="workflow-node">{done ? <Check size={15} /> : <Icon size={15} />}</span>{index < steps.length - 1 && <i />}</div><div className="workflow-card"><div className="workflow-head"><div><p className="eyebrow">{number} · {label}</p><h3>{title}</h3></div><span className="workflow-status">{done ? 'COMPLETE' : active ? 'LIVE' : 'WAITING'}</span></div><div className="workflow-content">{content}</div>{action && <div className="workflow-action">{action}</div>}</div></section>)}</div></>;
}
